; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

target datalayout = "e-p1:64:64:64:32-po2:64:64"

declare void @llvm.assume(i1)

define ptr @nonnull_minus_one(ptr nonnull %p) {
; CHECK-LABEL: define ptr @nonnull_minus_one(
; CHECK-SAME: ptr nonnull [[P:%.*]]) {
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr nusw i8, ptr [[P]], i64 -1
; CHECK-NEXT:    ret ptr [[GEP]]
;
  %gep = getelementptr i8, ptr %p, i64 -1
  ret ptr %gep
}

define ptr @unknown_minus_one(ptr %p) {
; CHECK-LABEL: define ptr @unknown_minus_one(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr i8, ptr [[P]], i64 -1
; CHECK-NEXT:    ret ptr [[GEP]]
;
  %gep = getelementptr i8, ptr %p, i64 -1
  ret ptr %gep
}

define ptr @aligned_minus_eight(ptr nonnull align 8 %p) {
; CHECK-LABEL: define ptr @aligned_minus_eight(
; CHECK-SAME: ptr nonnull align 8 [[P:%.*]]) {
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr nusw i8, ptr [[P]], i64 -8
; CHECK-NEXT:    ret ptr [[GEP]]
;
  %gep = getelementptr i8, ptr %p, i64 -8
  ret ptr %gep
}

define ptr @aligned_minus_nine(ptr nonnull align 8 %p) {
; CHECK-LABEL: define ptr @aligned_minus_nine(
; CHECK-SAME: ptr nonnull align 8 [[P:%.*]]) {
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr i8, ptr [[P]], i64 -9
; CHECK-NEXT:    ret ptr [[GEP]]
;
  %gep = getelementptr i8, ptr %p, i64 -9
  ret ptr %gep
}

define ptr @alignment_without_nonnull(ptr align 8 %p) {
; CHECK-LABEL: define ptr @alignment_without_nonnull(
; CHECK-SAME: ptr align 8 [[P:%.*]]) {
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr i8, ptr [[P]], i64 -8
; CHECK-NEXT:    ret ptr [[GEP]]
;
  %gep = getelementptr i8, ptr %p, i64 -8
  ret ptr %gep
}

define ptr @positive_offset(ptr nonnull %p) {
; CHECK-LABEL: define ptr @positive_offset(
; CHECK-SAME: ptr nonnull [[P:%.*]]) {
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr i8, ptr [[P]], i64 1
; CHECK-NEXT:    ret ptr [[GEP]]
;
  %gep = getelementptr i8, ptr %p, i64 1
  ret ptr %gep
}

define ptr @typed_gep_aligned(ptr nonnull align 4 %p) {
; CHECK-LABEL: define ptr @typed_gep_aligned(
; CHECK-SAME: ptr nonnull align 4 [[P:%.*]]) {
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr nusw i8, ptr [[P]], i64 -4
; CHECK-NEXT:    ret ptr [[GEP]]
;
  %gep = getelementptr i32, ptr %p, i64 -1
  ret ptr %gep
}

define ptr @typed_gep_unaligned(ptr nonnull %p) {
; CHECK-LABEL: define ptr @typed_gep_unaligned(
; CHECK-SAME: ptr nonnull [[P:%.*]]) {
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr i8, ptr [[P]], i64 -4
; CHECK-NEXT:    ret ptr [[GEP]]
;
  %gep = getelementptr i32, ptr %p, i64 -1
  ret ptr %gep
}

define ptr @assumed_nonnull(ptr %p) {
; CHECK-LABEL: define ptr @assumed_nonnull(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "nonnull"(ptr [[P]]) ]
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr nusw i8, ptr [[P]], i64 -1
; CHECK-NEXT:    ret ptr [[GEP]]
;
  %cmp = icmp ne ptr %p, null
  call void @llvm.assume(i1 %cmp)
  %gep = getelementptr i8, ptr %p, i64 -1
  ret ptr %gep
}

define ptr addrspace(1) @narrow_address(ptr addrspace(1) nonnull %p) {
; CHECK-LABEL: define ptr addrspace(1) @narrow_address(
; CHECK-SAME: ptr addrspace(1) nonnull [[P:%.*]]) {
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr nusw i8, ptr addrspace(1) [[P]], i32 -1
; CHECK-NEXT:    ret ptr addrspace(1) [[GEP]]
;
  %gep = getelementptr i8, ptr addrspace(1) %p, i64 -1
  ret ptr addrspace(1) %gep
}

define ptr addrspace(2) @all_ones_null(ptr addrspace(2) %p) {
; CHECK-LABEL: define ptr addrspace(2) @all_ones_null(
; CHECK-SAME: ptr addrspace(2) [[P:%.*]]) {
; CHECK-NEXT:    [[CMP_NOT:%.*]] = icmp eq ptr addrspace(2) [[P]], null
; CHECK-NEXT:    br i1 [[CMP_NOT]], label %[[ISNULL:.*]], label %[[NONNULL:.*]]
; CHECK:       [[NONNULL]]:
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr i8, ptr addrspace(2) [[P]], i64 -1
; CHECK-NEXT:    ret ptr addrspace(2) [[GEP]]
; CHECK:       [[ISNULL]]:
; CHECK-NEXT:    ret ptr addrspace(2) null
;
  %cmp = icmp ne ptr addrspace(2) %p, null
  br i1 %cmp, label %nonnull, label %isnull

nonnull:
  %gep = getelementptr i8, ptr addrspace(2) %p, i64 -1
  ret ptr addrspace(2) %gep

isnull:
  ret ptr addrspace(2) null
}

define ptr @dereferenceable(ptr dereferenceable(1) %p) {
; CHECK-LABEL: define ptr @dereferenceable(
; CHECK-SAME: ptr dereferenceable(1) [[P:%.*]]) {
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr nusw i8, ptr [[P]], i64 -1
; CHECK-NEXT:    ret ptr [[GEP]]
;
  %gep = getelementptr i8, ptr %p, i64 -1
  ret ptr %gep
}

define ptr @dereferenceable_null_valid(ptr dereferenceable(1) %p) #0 {
; CHECK-LABEL: define ptr @dereferenceable_null_valid(
; CHECK-SAME: ptr dereferenceable(1) [[P:%.*]]) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr i8, ptr [[P]], i64 -1
; CHECK-NEXT:    ret ptr [[GEP]]
;
  %gep = getelementptr i8, ptr %p, i64 -1
  ret ptr %gep
}

attributes #0 = { null_pointer_is_valid }
